# Generated by Django 5.2.6 on 2025-09-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='quantities_positive_int',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='quantities_positive_int'),
        ),
    ]
