# Generated by Django 5.2.6 on 2025-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("shopping", "0005_remove_category_quantities_positive_int_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="amount_as_positive",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="shopping_cu_email_a64f88_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["phone_number"], name="shopping_cu_phone_n_28c372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer"], name="shopping_or_custome_c20656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["amount"], name="shopping_or_amount_2c5cb6_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercategory",
            index=models.Index(
                fields=["customer", "order"], name="shopping_or_custome_84f0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercategory",
            index=models.Index(
                fields=["category"], name="shopping_or_categor_b85f87_idx"
            ),
        ),
        # migrations.AddConstraint(
        #     model_name="customer",
        #     constraint=models.CheckConstraint(
        #         condition=models.Q(("amount__gte", 0)), name="amount_as_positive"
        #     ),
        # ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="order_amount_as_positive"
            ),
        ),
    ]
