# Generated by Django 5.2.6 on 2025-09-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0006_remove_order_amount_as_positive_and_more"),
    ]

    # operations = [
    #     migrations.RemoveConstraint(
    #         model_name="customer",
    #         name="amount_as_positive",
    #     ),
    # ]
